### PR TITLE
Popular referral dashboard

### PR DESCRIPTION
**Pull request by neurosnap**
Still WIP, just want to set up the pull request for future reference. #18

### CODE REVIEW

**Comment by neurosnap** [comment]
http://bl.ocks.org/nswamy14/e28ec2c438e9e8bd302f

**Comment by neurosnap** [comment]
This dashboard is ready to be reviewed @bendik @migreva

**Comment by migreva** [comment]
Can you update it so it can be merged cleanly?

**Comment by migreva** [comment]
The code looks good

**Pull request merged**
