### PR TITLE
enforce trailing commas

### PR DESCRIPTION
**Pull request by neurosnap**
This change will force trailing commas. 

The reason why we would want to enforce trailing commas is because it's easier to move properties in an object around without having to add/remove commas.  It will also clean up our commits.

### CODE REVIEW

**Comment by andreyvit** [comment]
+1 for enforcing in all projects

**Comment by migreva** [comment]
Doesn't airbnb eslint already enforce this?

**Comment by migreva** [comment]
Wait, this code change is about underscores, not commas

**Comment by neurosnap** [comment]
woops you're right.  It looks like airbnb might have added trailing commas since i've last updated: https://github.com/airbnb/javascript#commas--dangling

**Pull request closed without merging**
